<?php echo $this->doctype(); ?>

<html xmlns:ng="http://angularjs.org" ng-app="flickr-scraper" lang="en">
    <head>
    	<?php echo $this->headTitle('ZF2 '. $this->translate('Flickr Scraper'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <meta charset="utf-8">
         <?php echo $this->headMeta()
            					->appendName('viewport', 'width=device-width, initial-scale=1.0')
								->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <link href="<?php echo $this->basepath()."/css/bootstrap.no-icons.min.css" ?>" rel="stylesheet">
        <link href="http://netdna.bootstrapcdn.com/font-awesome/2.0/css/font-awesome.css" rel="stylesheet">
        
        <script src="<?php echo $this->basepath()."/js/angular.min.js" ?>"></script>
        <script type="text/javascript">
			var sortingOrder = 'name';
		</script>
    </head>
<body>

<?php echo $this->content ?>

<?php echo $this->inlineScript() ?>
</body>
</html>